### ISSUE TITLE
Store receivers data by database, file or something else?

### ISSUE THREAD

**Issue by anthonypillot** [size-up/freegamescatcher#13]
We need to store all data into something.. database, file, something else?

The goal is to store:
- List of email receivers
- Our cache to used to compare data: today compare to yesterday to overwrite any changes.

**Comment by Bedhiver** [comment]
- Mapping data from Epic Games
- Save mappedObject into json file called `cache.json`

**Comment by anthonypillot** [comment]
We have decided that we'll use the Google Drive API to manage our data.
